version: '3.7'

networks:
  default:
    driver: bridge

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    networks:
      - default
    image:
      hackathon
    ports:
      - "8000:8000"
    command: poetry run hackathon/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    hostname: db
    networks:
      - default
    environment:
      DB_USER: hackathon
      DB_PASSWORD: password
      DB_NAME: ai_cup
  bot:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image:
      local-bot
    ports:
      - "3001:3001"
    command: poetry run hackathon/manage.py runbot
    depends_on:
      - db